[tool.poetry]
name = "peps-ad"
version = "0.1.0"
description = "Code to solve PEPS network using AD methods"
authors = ["Philipp Schmoll", "Augustine Kshetrimayum", "Frederik Wilde", "Jan Naumann <j.naumann@fu-berlin.de>"]
license = "GPL-3.0"
readme = "README.md"
packages = [{include = "peps_ad"}]

[tool.poetry.dependencies]
python = ">=3.7,<3.10"
numpy = "^1.21.2"
scipy = "^1.7.1"
jax = {extras = ["cuda111"], version = "^0.2.20"}
tensornetwork = "^0.4.5"
jaxlib = {version = "0.1.71+cuda111", source = "jax-cuda"}

[tool.poetry.dev-dependencies]
black = "^21.8-beta.0"
ipython = "^7.27.0"
pylint = "^2.10.2"
flake8 = "^3.9.2"
mypy = "^0.910"


[[tool.poetry.source]]
name = "jax-cuda"
url = "https://janluca.github.io/pypi/"
default = false
secondary = false

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
