[tool.poetry]
name = "peps-ad"
version = "0.3.2"
description = "Library to solve iPEPS networks using AD methods"
authors = ["Jan Naumann <j.naumann@fu-berlin.de>", "Philipp Schmoll <philipp.schmoll@fu-berlin.de>", "Frederik Wilde"]
license = "GPL-3.0"
readme = "README.md"
packages = [{include = "peps_ad"}]

[tool.poetry.dependencies]
python = ">=3.9,<4.0"
numpy = ">=1.21.2"
scipy = ">=1.7.1"
jax = {extras = ["cpu"], version = ">=0.3.16"}
tensornetwork = ">=0.4.5"
poethepoet = ">=0.10.0"
h5py = ">=3.6.0"
tqdm = {extras = ["notebook"], version = ">=4.64.1"}
tqdm-loggable = "^0.1.3"

[tool.poetry.dev-dependencies]
black = ">=21.8-beta.0"
ipython = ">=7.27.0"
pylint = ">=2.10.2"
flake8 = ">=3.9.2"
mypy = ">=0.910"
jupyter = ">=1.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poe.tasks]
use-cuda = "pip install --upgrade 'jax[cuda]' -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html"
